schedules:
  timeslots:
    path: /app/configs/schedules.json
  kitchen:
    path: /app/configs/rooms.json

otlp:
  tracing:
    export-enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver